web1_projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from app_web1.views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('index/', IndexView.as_view(), name='index'),

    path('pokemons/', include('app_web1.web1_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

app_web1/models.py
from django.db import models
from django.utils.html import mark_safe

# Create your models here. 
class Pokemon(models.Model):
    TYPE_CHOICES = [
        ('grass', 'Grass'),
        ('fire', 'Fire'),
        ('water', 'Water'),
        ('electric', 'Electric'),
        ('psychic', 'Psychic'),
        ('ice', 'Ice'),
        ('bug', 'Bug'),
        ('rock', 'Rock'),
        ('ghost', 'Ghost'),
        ('dragon', 'Dragon'),
        ('fairy', 'Fairy'),
        ('fighting', 'Fighting'),
        ('normal', 'Normal'),
        ('poison', 'Poison'),
        ('steel', 'Steel'),
        ('dark', 'Dark'),
        ('flying', 'Flying'),
        ('ground', 'Ground')
    ]

    name = models.CharField(max_length=100)
    type_primary = models.CharField(max_length=20, choices=TYPE_CHOICES)
    type_secondary = models.CharField(max_length=20, choices=TYPE_CHOICES, null=True, blank=True)
    number = models.IntegerField()
    gen = models.IntegerField()
    image = models.FileField(upload_to='pokemons/')

    def __str__(self):
        return self.name
    
    def formatted_number(self):
        return str(self.number).zfill(4)
    
    def img(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" style="width: 50px; height: auto;" />')
        return "No Image"
    
class CustomPokemon(models.Model):
    TYPE_CHOICES = [
        ('grass', 'Grass'),
        ('fire', 'Fire'),
        ('water', 'Water'),
        ('electric', 'Electric'),
        ('psychic', 'Psychic'),
        ('ice', 'Ice'),
        ('bug', 'Bug'),
        ('rock', 'Rock'),
        ('ghost', 'Ghost'),
        ('dragon', 'Dragon'),
        ('fairy', 'Fairy'),
        ('fighting', 'Fighting'),
        ('normal', 'Normal'),
        ('poison', 'Poison'),
        ('steel', 'Steel'),
        ('dark', 'Dark'),
        ('flying', 'Flying'),
    ]

    name = models.CharField(max_length=100)
    type_primary = models.CharField(max_length=20, choices=TYPE_CHOICES)
    type_secondary = models.CharField(max_length=20, choices=TYPE_CHOICES, null=True, blank=True)
    number = models.IntegerField()
    image = models.FileField(upload_to='custom_pokemons/')

    def __str__(self):
        return self.name

class Game(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    release_date = models.DateField()
    image = models.FileField(upload_to='games/')


    def __str__(self):
        return self.name
    
    def img(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" style="width: 50px; height: auto;" />')
        return "No Image"

app_web1/forms.py
from django import forms 
from .models import CustomPokemon, Game

class CustomPokemonForm(forms.ModelForm):
    class Meta:
        model = CustomPokemon 
        fields = '__all__' 

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = '__all__'  

app_web1/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from app_web1.models import Pokemon, CustomPokemon, Game


class CustomRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

class CustomLoginView(LoginView):
    template_name = 'login.html'

class CustomLogoutView(LogoutView):
    next_page = 'login'  


class IndexView(LoginRequiredMixin, TemplateView):
    model = Pokemon
    template_name = 'index.html' 
    context_object_name = 'pokemons'
    login_url = 'login'

    

    def dispatch(self, request, *args, **kwargs):
        # Impedir que a página index seja armazenada em cache
        response = super().dispatch(request, *args, **kwargs)
        response['Cache-Control'] = 'no-store'
        response['Pragma'] = 'no-cache'
        response['Expires'] = '0'
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pokemons'] = Pokemon.objects.all().order_by('number')
        context['generations'] = list(range(1, 10))
        return context
    
class CustomPokemonView(LoginRequiredMixin, ListView):
    model = CustomPokemon
    queryset = CustomPokemon.objects.all()

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        response['Cache-Control'] = 'no-store'
        response['Pragma'] = 'no-cache'
        response['Expires'] = '0'
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pokemons'] = CustomPokemon.objects.all().order_by('number')
        context['generations'] = list(range(1, 10))
        return context
    
class CustomPokemonCreate(LoginRequiredMixin, CreateView):
    model = CustomPokemon
    fields = '__all__'
    success_url = reverse_lazy('app_web1:list')
    
class CustomPokemonUpdate(LoginRequiredMixin, UpdateView):
    model = CustomPokemon
    fields = '__all__'
    success_url = reverse_lazy('app_web1:list')

class CustomPokemonDelete(LoginRequiredMixin, DeleteView):
    queryset = CustomPokemon.objects.all()
    success_url = success_url = reverse_lazy('app_web1:list')

class GamesView(LoginRequiredMixin, ListView):
    model = Game
    queryset = Game.objects.all()
    paginate_by = 6
    

    def dispatch(self, request, *args, **kwargs):
        # Impedir que a página index seja armazenada em cache
        response = super().dispatch(request, *args, **kwargs)
        response['Cache-Control'] = 'no-store'
        response['Pragma'] = 'no-cache'
        response['Expires'] = '0'
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['games'] = Game.objects.all().order_by('release_date')
        return context
    
class GameDetailView(LoginRequiredMixin, DetailView):
    model = Game
    queryset = Game.objects.all()

templates/app_web1/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokedex</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href= {% static "./styles/style.css" %}>
</head>
<body>
    <!--header com a navegação e o darkMode, botão saduiche na responsividade-->
    <header>
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid d-flex">
                <h1 class="d-flex align-items-center">
                    <p class="m-0" id="titlePoke">P</p>
                    <?xml version="1.0" ?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
                    <svg class="m-0" fill="#fff" width="2.8rem" height="2.8rem" viewBox="0 0 512 512" data-name="Layer 1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"><title/>
                        <path d="M450.46,256.09C449.35,175.17,399.81,102.71,324,73.79,247.59,44.67,157.49,69,105.82,132.13,54.4,195,46.61,285.58,88.49,355.68c41.8,69.95,123.74,106,203.55,91.63,
                        91-16.37,156.14-98.12,158.35-189.14A20.16,20.16,0,0,0,450.46,256.09ZM119.05,174.38C152.76,118,220.23,87,285,99.43c69.4,13.29,120.43,70.47,128.83,139H318.41c-8.26-27.36-32-48-62.62-48-29.65,
                        0-55.15,20.65-63.11,48H97.74A158,158,0,0,1,119.05,174.38ZM286.13,256.1c-2,38.75-60.67,39.4-60.67,0S284.17,217.33,286.13,256.1Zm24,149.79C246.85,428.58,175,408.74,132.3,356.82a157.53,157.53,
                        0,0,1-34.57-83H192.6c7.91,27.39,33.7,48,63.19,48,30.67,0,54.36-20.68,62.62-48h95.45C406.61,333,367.54,385.32,310.14,405.89Z"/>
                    </svg>
                    <p class="m-0" id="titleView">ke</p>
                    <p class="m-0" id="titleView">View</p>
                </h1>
                
                <!--botão sanduiche-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <!--área de navegação-->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto d-flex text-center">
                        <li class="nav-item">
                            <a href="{% url 'index'%}">Pokedex</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app_web1:list' %}">CustomDex</a>
                        </li>
                        <li class="nav-item">
                            <a href=" {% url 'app_web1:game_list' %}">Games</a>
                        </li>
                        <li class="nav-item">
                            <a href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a href="#contact-info">Contact</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item d-flex justify-content-center">
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button class="nav-link logout-btn" type="submit" >Logout</button>
                            </form>
                        </li>
                        {% endif %}
                    </ul>
                    
                    <!--Dark mode-->           
                    <div class="d-flex justify-content-center align-items-center">
                        <button class="btn shadow-sm bg-primary" id="darkModeBtn">
                            <svg id="sunIcon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -930 960 960" width="24px" fill="#ffffff">
                                <path d="M480-360q50 0 85-35t35-85q0-50-35-85t-85-35q-50 0-85 35t-35 85q0 50 35 85t85 35Zm0 80q-83 0-141.5-58.5T280-480q0-83 58.5-141.5T480-680q83 0 141.5 58.5T680-480q0 
                                83-58.5 141.5T480-280ZM200-440H40v-80h160v80Zm720 0H760v-80h160v80ZM440-760v-160h80v160h-80Zm0 720v-160h80v160h-80ZM256-650l-101-97 57-59 96 100-52 56Zm492 496-97-101 53-55 
                                101 97-57 59Zm-98-550 97-101 59 57-100 96-56-52ZM154-212l101-97 55 53-97 101-59-57Zm326-268Z"/>
                            </svg>
                            <svg id="moonIcon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#181a1b">
                                <path d="M480-120q-150 0-255-105T120-480q0-150 105-255t255-105q14 0 27.5 1t26.5 3q-41 29-65.5 75.5T444-660q0 90 63 153t153 63q55 0 101-24.5t75-65.5q2 13 3 26.5t1 27.5q0 150-105 
                                255T480-120Zm0-80q88 0 158-48.5T740-375q-20 5-40 8t-40 3q-123 0-209.5-86.5T364-660q0-20 3-40t8-40q-78 32-126.5 102T200-480q0 116 82 198t198 82Zm-10-270Z"/>
                            </svg>
                        </button>
                    </div>
                    
                </div>
            </div>
        </nav>
    </header>

    <!--Lista de Pokemons-->
    <!--Área de pesquisa-->
    {% block searchArea %}
    <section class="container p-3 mt-4 d-flex justify-content-center">
        <div class="search-area container-pokelist-up d-flex gap-2">
            <div class="container-pokelist-up d-flex gap-2">
                <button class="btn border bg-primary text-white d-flex justify-content-center" id="invertListBtn">
                    Ascending
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#fff" class="bi bi-arrows-vertical" viewBox="-2 -1 16 16">
                        <path d="M8.354 14.854a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 13.293V2.707L6.354 3.854a.5.5 0 1 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 
                        2.707v10.586l1.146-1.147a.5.5 0 0 1 .708.708z"/>
                    </svg>
                </button>
            </div>
                
            <div class="container-pokelist-down d-flex gap-2">

                <input type="text" class="form-cotrol w-auto rounded border-primary" placeholder="Pesquisar Pokemon" id="searchInput">
            
                <button class="btn border bg-primary m-0" id="clearBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#fff" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2z"/>
                        <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466"/>
                    </svg>
                </button>

                <button class="btn border bg-primary m-0" id="favListBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#fff" class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                    </svg>
                </button>
            </div>
        </div>
    </section>
    {% endblock searchArea %}

    <!--Pokedex-->
    <section class="pokedex-list container mt-4" id="pokemonContainer">
        <div class="row g-3 align-items-center mb-4">

            {% block content %}
            {% for pokemon in pokemons %}
            <div class="pokemon-card gen-{{ pokemon.gen }} col-6 xs col-sm-4 col-md-4 col-lg-2 col-xl-2">
                <div class="card">
                    <div class="card-fav d-flex justify-content-between m-1">
                        <div class="card-number d-flex align-items-center p-1 fw-bold">N° {{ pokemon.number }}</div>
                        <button class="fav-heart-btn btn btn-sm border">
                            <svg class="heart-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#d2d2d2" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                            </svg>
                        </button>
                    </div>
            
                    <img src="{{ pokemon.image.url }}" class="poke-img m-3 mb-0 mt-0" alt="{{ pokemon.name }}">
                    <div class="card-body">
                        <h5 class="card-title m-0 bold-text">{{ pokemon.name }}</h5>
                        <div class="card-type d-flex align-items-center gap-1">
                            <p class="p-1 px-xs px-sm-2 px-md-2 px-lg-2 pxl-xl-4 m-0 border rounded small-text bg-{{ pokemon.type_primary|lower }} text-white">{{ pokemon.type_primary|capfirst }}</p>
                            {% if pokemon.type_secondary %}
                            <p class="p-1 px-xs px-sm-2 px-md-2 px-lg-2 pxl-xl-4 m-0 border rounded small-text bg-{{ pokemon.type_secondary|lower }} text-white">{{ pokemon.type_secondary|capfirst }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endblock %}
        </div>
    </section>
    

    <!--Rodapé-->
    <footer class="bg-primary text-white p-4">
        <div class="container">
            <div class="d-flex flex-column">
                <div class="mb-3 mt-1" id="contact-info">
                    <h5 class="m-0">Contacts:</h5>
                    <p class="m-0">Email: PokeView@gmail.com</p>
                    <p class="m-0">Telefone: (00) 91234-5678</p>
                </div>

            <div class="social-media">
                <h5 class="m-0 mt-2">Social Media:</h5>
                <ul class="list-unstyled d-flex mt-2">
                    <li class="social-media mx-2">
                        <a href="#" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#fff" class="bi bi-twitter-x" viewBox="0 0 16 16">
                                <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                            </svg>
                        </a>
                    </li>
                    <li class="social-media mx-2">
                        <a href="#" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#fff   " class="bi bi-instagram" viewBox="0 0 16 16">
                                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                            </svg>
                        </a>
                    </li>
                    <li class="social-media mx-2">
                        <a href="#" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#fff" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                            </svg>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="d-flex justify-content-center mt-3">
            <small>content & design © PokeView, 2024. Pokémon images & names © 1995-2024 Nintendo/Game Freak.</small> 
        </div>
    </footer>
    
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src= {% static "./js/script.js" %} ></script>
</body>
</html>

templates/app_web1/custompokemon_confirm_delete.html
{% extends "app_web1/base.html" %}

{% block searchArea %}
{% endblock searchArea %}

{% block content %}
    <div class="d-flex justify-content-center">
        <h1 class="p-2 mt-4 rounded bg-primary text-white ">Are you sure you want to delete Pokemon {{ object.name }}?</h1>
    </div>
    <form action="." method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-center">
            <div class="pokemon-card col-6">
                <div class="card">
                    <div class="card-fav d-flex justify-content-between m-1">
                        <div class="card-number d-flex align-items-center p-1 fw-bold">N° {{ object.number }}</div>
                        <button class="fav-heart-btn btn btn-sm border">
                            <svg class="heart-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#d2d2d2" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                            </svg>
                        </button>
                    </div>
            
                    <img src="{{ object.image.url }}" class="poke-img m-2 mb-0 mt-0" alt="{{ object.name }}">
                    <div class="card-body">
                        <h5 class="card-title m-0 bold-text">{{ object.name }}</h5>
                        <div class="card-type d-flex align-items-center gap-1">
                            <p class="p-1 px-xs px-sm-2 px-md-2 px-lg-2 pxl-xl-4 m-0 mt-3 border rounded small-text bg-{{ object.type_primary|lower }} text-white">{{ object.type_primary|capfirst }}</p>
                            {% if object.type_secondary %}
                            <p class="p-1 px-xs px-sm-2 px-md-2 px-lg-2 pxl-xl-4 m-0 mt-3 border rounded small-text bg-{{ object.type_secondary|lower }} text-white">{{ object.type_secondary|capfirst }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center gap-2">
            <input class="mt-1 mb-1 btn rounded bg-primary text-white" type="submit" value="Sim">
            <input class="mt-1 mb-1 btn rounded bg-primary text-white" type="reset" value="Não" onclick="location.href= '{% url 'app_web1:list' %}'">
        <div>
    </form>
{% endblock content %}

templates/app_web1/custompokemon_form.html
{% extends "app_web1/base.html" %}

{% block searchArea %}
{% endblock searchArea %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label class="p-1 mt-5 rounded bg-primary text-white" for="{{ form.name.id_for_label }}">Name:</label>
        {{ form.name }}  
    </div>
    <div class="form-group">
        <label class="p-1 mt-2 rounded bg-primary text-white" for="{{ form.number.id_for_label }}">Number:</label>
        {{ form.number }}  
    </div>
    <div class="form-group">
        <label class="p-1 mt-2 rounded bg-primary text-white" for="{{ form.type_primary.id_for_label }}">1° Type:</label>
        {{ form.type_primary }}  
    </div>
    <div class="form-group">
        <label class="p-1 mt-2 rounded bg-primary text-white" for="{{ form.type_secondary.id_for_label }}">2° Type:</label>
        {{ form.type_secondary }}  
    </div>
    <div class="form-group">
        <label class="p-1 mt-2 mb-1 rounded bg-primary text-white"  for="{{ form.image.id_for_label }}">Image:</label>
        {{ form.image }}  
    </div>
    <input class="p-1 mt-1 mb-5 btn rounded bg-primary text-white" type="submit" value="Salvar">
    <input class="p-1 mt-1 mb-5 btn rounded bg-primary text-white" type="reset" value="Cancelar" onclick="location.href = {% url 'app_web1:list' %}">
</form>
{% endblock content %}

templates/app_web1/game_detail.html
{% extends "app_web1/base.html" %}

{% block searchArea %}{% endblock searchArea %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-center">
            <div class="pokemon-card col-6 ">
                <div class="card d-flex ">
                    <div class="d-flex">
                        <div>
                            <img src="{{ object.image.url }}" class="poke-img m-2 mb-0" alt="{{ object.name }}">
                        </div>

                        <div class="card-body">
                            <div class="d-flex nowrap gap-2">
                                <p class="bold-text">Title:</p>
                                <p>{{ object.name }}</p>
                            </div>

                            <div class="d-flex nowrap gap-2">
                                <p class="bold-text">Release:</p>
                                <p>{{ object.release_date }}</p>
                            </div>

                            <p class="m-0 bold-text">Description:</p>
                            <p class="m-0">{{ object.description }}</p>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center gap-2">
            <input class="mt-1 mb-1 btn rounded bg-primary text-white" type="reset" value="Voltar" onclick="location.href= '{% url 'app_web1:game_list' %}'">
        <div>
    </form>
{% endblock content %}